---
name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: docker.io/library/golang:${{ matrix.go }}
    strategy:
      matrix:
        go: ['1.22']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: make binaries
        run: make all
      - name: perform tests
        run: go test -v ./...
